
--- 
- name: Deploy the springboot application
  hosts: all 
  become: yes
  tasks:
    - name: this for when the distribution is not ubuntu and cenos 
      fail:
       msg: "this playbook will work for ubuntu os another distrubution will be coming soon"
      when: ansible_facts['distribution'] != "Ubuntu"  and ansible_facts['distribution'] != "CentOS"

    - name: update the ubuntu packages and install openjdk-11-jdk
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      notify:
        - debug message for java 
      when: ansible_facts['distribution'] == "Ubuntu" 
    - name: java installation for centos
      yum:
        name: "{{ java_package }}"
        state: present
      when: ansible_facts['distribution'] == "CentOS"
    - name: To create the dirctory /usr/share/springpetclinic
      file:
        path: "{{ app_dir }}"
        state: directory
      notify:
        - debug message for create directory  
    - name: Download file from a file path
      get_url:
       url: "{{ app_download_url }}"
       dest: "{{ app_file_name }}"    

    - name: create the user as springboot
      user:
        name: "{{ app_user }}"
        password: "{{ app_password }}"
        state: present 
      notify:
        - Change the ownership to springboot
    - name: Change the ownership to springboot
      file: 
        path:  "{{ app_file_name }}"
        owner: "{{ app_user }}"
        mode: 500
        state: file    
    - name: copy the springboot.service
      copy:
        src: springboot.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: enable start and restart the springboot application 
      systemd:
        name: springboot.service
        enabled: yes
        state: started
  handlers:
    - name: debug message for java
      debug:
        msg: "java with packages {{ java_package }} are installed"

    - name: debug message for create directory
      debug: 
        msg: "Directory is created by {{ app_dir }}"   

    
  



