
--- 
- name: Deploy the springboot application
  hosts: ubuntu
  become: yes
  vars:
    java_package: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic
    app_dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    app_download_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_user: springboot
    app_password: springboot
    test_vars: this is for install java packages
  tasks:
    - name: Display the javapackages
      debug:
        var: java_package
    - name: checking variable
      debug:
        var: test_vars    
    - name: update the ubuntu packages and install openjdk-11-jdk
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: To create the dirctory /usr/share/springpetclinic
      file:
        path: "{{ app_dir }}"
        state: directory
    - name: download the springboot
      get_url:
        url: "{{ app_download_url }}"
        dest: "{{ app_dest }}"
        state: present 
    - name: create the user as springboot
      user:
        name: "{{ app_user }}"
        password: "{{ app_password }}"
        state: present 
    - name: Change the ownership to springboot
      file: 
        path:  "{{ app_dest }}"
        owner: springboot
        mode: 500
        state: file
    - name: copy the springboot.service
      copy:
        src: springboot.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: enable strat and restart the springboot application 
      systemd:
        name: springboot.service
        enabled: yes
        state: started





